Update CreateNymHD to accept -1 for automatic indexing. Update transaction activity thread tests

diff --git a/scripts/git_hooks/pre-commit b/scripts/git_hooks/pre-commit
--- a/scripts/git_hooks/pre-commit
+++ b/scripts/git_hooks/pre-commit
@@ -1,9 +1,18 @@
 #!/bin/sh
 
-if ! command -v clang-format >/dev/null &&
-        ! command -v clang-format-3.8 >/dev/null ; then
-    echo -n "error: please install clang-format in order to be able"
-    echo    " to use this pre-commit git-hook"
+clang_bin=clang-format
+
+if ! command -v clang-format >/dev/null ; then
+    clang_bin=clang-format-6.0
+    if ! command -v clang-format-6.0 >/dev/null ; then
+        echo -n "error: please install clang-format v6.0 in order to be able"
+        echo    " to use this pre-commit git-hook"
+        exit 1
+    fi
+fi
+
+if ! (${clang_bin} --version | grep 6.0) ; then
+    echo "Checking for clang-format version 6.0 ... failed"
     exit 1
 fi
 
